"""added payment table

Revision ID: 86584f01a25f
Revises: 98dd3eb23b2b
Create Date: 2025-07-24 17:59:26.316340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86584f01a25f'
down_revision = '98dd3eb23b2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('payment_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('amount', sa.Float(precision=10, asdecimal=2), nullable=False),
    sa.Column('category', sa.Enum('bills', 'subscription', 'loan', 'tax', 'other', name='category_enum'), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', 'overdue', 'cancelled', name='status_enum'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('phone_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=15),
               nullable=True)
        batch_op.drop_column('Userid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Userid', sa.INTEGER(), nullable=False))
        batch_op.alter_column('phone_number',
               existing_type=sa.String(length=15),
               type_=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.drop_column('id')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_user_id'))

    op.drop_table('payment')
    # ### end Alembic commands ###
